name: frag-api
channels:
    - conda-forge
dependencies:
    - rdkit
    - numpy=1.19.4
    - pip
    - pip:
        - "--editable=git+https://github.com/xchem/pandda_gemmi.git@master#egg=pandda_gemmi"
        - "--editable=git+https://github.com/xchem/fragalysis-api.git@master#egg=fragalysis-api"
        - gemmi
